### ISSUE TITLE
How to compile in Arduino

### ISSUE THREAD

**Issue by rmilyard** [prusa3d/MM-control-01#184]
This is the error I get when trying to compile with Arduino 1.8.5

Arduino: 1.8.5 (Windows 10), Board: "Original Prusa i3 MK3 Multi Material 2.0 upgrade"

In file included from sketch\main.cpp:20:0:

version.h:7: error: stray '$' in program

 static const uint16_t fw_buildnr = ${GIT_PARENT_COMMITS}; //!< number of commits preceeding current HEAD

                                    ^

version.h:7: error: 'GIT_PARENT_COMMITS' was not declared in this scope

 static const uint16_t fw_buildnr = ${GIT_PARENT_COMMITS}; //!< number of commits preceeding current HEAD

                                      ^~~~~~~~~~~~~~~~~~

exit status 1
stray '$' in program

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
